version: '3.8'

services:
  aprohirdeto-ui:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - aprohirdeto-network

networks:
  aprohirdeto-network:
    driver: bridge